name = "new-option"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "new-option-db"
database_id = "377fe925-f923-42bc-80b3-1889d7f30408"
migrations_dir = "migrations"

[[services]]
binding = "WORKER"
service = "new-option"
